create table if not exists cvk.candidate (
 hash numeric,
 uri text unique,
 name text,
 electionRegion numeric,
 partyAssociation text,
 partyListNum numeric,
 photo text,
 cvkRegistrationNum text,
 cvkRegistrationDate date,
 registrationNum numeric,
 registrationDate date,
 isCancelled bool,
 cancellationReason text,
 notParsed json,
 gender bool,
 birthday date,
 canApply bool,
 originCountry text,
 party text,
 partyNum numeric,
 education text,
 employment json,
 city text,
 subject text,
 notParsedDetails json,
 created timestamp default now(),
 primary key(uri, hash)
);
