version: '3.1'

services:

  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cvk

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  crawler:
    image: default/cvk-crawler
    restart: always
    volumes:
      - ./config:/app/config
